services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: golang:1.20.2
    init: true
    volumes:
      - go:/go
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

volumes:
  go:
    name: "go"
